[workspace]
members = [
  ".",
  "binum-macros"
]

[package]
name = "binum"
version = "0.0.1"
edition = "2021"
authors = ["Techassi <git@techassi.dev>"]
description = "binum is a small library to work with binary (network) data"
repository = "https://github.com/Techassi/binum"
homepage = "https://github.com/Techassi/binum"
categories = ["encoding", "parsing", "network-programming"]
keywords = ["binary", "numbers", "network"]

[dependencies]
binum-macros = { path = "binum-macros" }
