[workspace]
members = [
  ".",
  "binbuf-derive",
  "binbuf-macros"
]

[package]
name = "binbuf"
version = "0.0.1"
edition = "2021"
authors = ["Techassi <git@techassi.dev>"]
description = "binbuf is a small library to work with binary (network) data"
repository = "https://github.com/Techassi/binbuf"
homepage = "https://github.com/Techassi/binbuf"
categories = ["encoding", "parsing", "network-programming"]
keywords = ["binary", "numbers", "network"]

[features]
full = ["derive", "macros"]
derive = []
macros = []

[dependencies]
binbuf-derive = { path = "binbuf-derive" }
binbuf-macros = { path = "binbuf-macros" }
thiserror = "1.0.38"

[[test]]
name = "test_read"
path = "tests/read/mod.rs"

[[test]]
name = "test_read_derive_enum"
path = "tests/read/read_derive_enum.rs"

[[test]]
name = "test_write"
path = "tests/write/mod.rs"
