[package]
name = "binbuf-derive"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.107", features = ["derive", "extra-traits"] }
proc-macro2 = "1.0.49"
structmeta = "0.1.5"
quote = "1.0.23"
